# Custom dataset

# dataset root dir
dataset: 
  cityscapes: 
    dataset_dir: /home/pc/workspace/dataset/cityscapes # foler that contains leftImg8bit/
    num_class: 19
    with_baockground: True # num_class = num_class + 1 if with_baockground == True
  coco: 
    dataset_dir: /home/pc/workspace/dataset/coco2017 # folder that contains images/.
    num_class: 21
