# Custom dataset

# dataset root dir
dataset: 
  cityscapes: 
    dataset_dir: /root/ghz_ws/cityscapes # foler that contains leftImg8bit/
    # dataset_dir: /home/pc/workspace/dataset/cityscapes # foler that contains leftImg8bit/
    group: True
    with_baockground: False # num_class = num_class + 1 if with_baockground == True , but it is only useful when group = False
  coco: 
    dataset_dir: /root/ghz_ws/coco # folder that contains images/.
