# Custom dataset

# dataset root dir
dataset: 
  cityscapes: 
    dataset_dir: /home/pc/workspace/dataset/cityscapes # foler that contains leftImg8bit/
    group: True
    with_baockground: True # num_class = num_class + 1 if with_baockground == True , but it is only useful when group = False
  coco: 
    dataset_dir: /home/pc/workspace/dataset/coco2017 # folder that contains images/.
    num_class: 21
